{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "k8s-object-syncer.labels" $ | nindent 4 }}
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-cluster"
rules:
- verbs: ["list", "get", "watch"]
  apiGroups: [""]
  resources: ["namespaces"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "k8s-object-syncer.labels" $ | nindent 4 }}
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-cluster"
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-object-syncer.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-cluster"
{{- end }}

