{{- if .Values.serviceAccount.create -}}
{{- range $index, $sourceNamespace := .Values.sourceNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "k8s-object-syncer.labels" $ | nindent 4 }}
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-source"
{{- if ne $sourceNamespace "*" }}
  namespace: "{{ $sourceNamespace }}"
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
rules:
  {{- range $index, $r := $.Values.allowedResources }}
- apiGroups:  
    {{- toYaml $r.apiGroups | nindent 8 }}
  resources: 
    {{- toYaml $r.resources | nindent 8 }}
  verbs: ["list", "get", "watch", "patch"]
  {{- end }}  
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "k8s-object-syncer.labels" $ | nindent 4 }}
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-source"
{{- if ne $sourceNamespace "*" }}
  namespace: "{{ $sourceNamespace }}"
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-object-syncer.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if ne $sourceNamespace "*" }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-source"
{{- end }}
{{- end }}

