{{- if .Values.serviceAccount.create -}}

{{ $namespaces := (len (.Values.watchNamespaces | default list)) }}
{{ if and (eq $namespaces 1) (not (has "*" .Values.watchNamespaces)) }} 
{{ $namespaces = .Values.watchNamespaces }}
{{else}}
{{ $namespaces = list "*" }}
{{end}}

{{- range $index, $watchNamespace := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "k8s-object-syncer.labels" $ | nindent 4 }}
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-watch"
{{- if ne $watchNamespace "*" }}
  namespace: "{{ $watchNamespace }}"
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
rules:
- apiGroups: ["sync.rustrial.org"]
  resources: ["objectsyncs", "objectsyncs/status"]
  verbs: ["list", "get", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "k8s-object-syncer.labels" $ | nindent 4 }}
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-watch"
{{- if ne $watchNamespace "*" }}
  namespace: "{{ $watchNamespace }}"
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-object-syncer.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if ne $watchNamespace "*" }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: "{{ include "k8s-object-syncer.serviceAccountName" $ }}-watch"
{{- end }}
{{- end }}

