[package]
name = "rustrial-k8s-object-syncer"
version = "0.1.0"
edition = "2018"
license = "Unlicense OR MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
opentelemetry = "0.15.0"
opentelemetry-prometheus = "0.8.0"
prometheus = "0.12.0"
anyhow = { version = "1.0.42", features = ["std"] }
thiserror = "1.0.26"
tokio = { version = "1.9.0", features = ["full"] }
futures = "0.3.16"
kube = { version = "0.58.1", default-features = false, features = [
    "client",
    "rustls-tls",
    "derive",
    "jsonpatch",
] }
json-patch = "0.2.6"
kube-runtime = "0.58.1"
k8s-openapi = { version = "0.12.0", default-features = false, features = [
    "v1_20",
] }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
hyper = { version = "0.14.11", features = ["server", "http1", "tcp"] }
rustrial-k8s-object-syncer-apis = { path = "../rustrial-k8s-object-syncer-apis" }
