[package]
name = "rustrial-k8s-object-syncer"
version = "0.2.0"
edition = "2021"
license = "Unlicense OR MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
log = "0.4.17"
env_logger = "0.11.3"
opentelemetry = "0.23.0"
opentelemetry_sdk = "0.23.0"
opentelemetry-prometheus = "0.16.0"
prometheus = "0.13.0"
anyhow = { version = "1.0.57", features = ["std"] }
thiserror = "1.0.26"
tokio = { version = "1.18.5", features = ["full"] }
futures = "0.3.21"
kube = { workspace = true, features = [
    "client",
    "rustls-tls",
    "derive",
    "jsonpatch",
] }
json-patch = "^1.4.0"
kube-runtime = "0.91.0"
k8s-openapi = { workspace = true, default-features = false, features = [
    "v1_30",
    "schemars",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
hyper = { version = "^1.3.1", features = ["server", "http1"] }
http-body-util = "^0.1"
hyper-util = { version = "^0.1", features = ["http1", "server"] }
rustrial-k8s-object-syncer-apis = { path = "../rustrial-k8s-object-syncer-apis" }
